### ISSUE TITLE
Error autentificación en backend

### ISSUE THREAD

**Issue by catalinaortegacalderon** [IIC2513/Syllabus-S2#2]
Hola! 

Estoy siguiendo las capsulas pero obtengo un error de autenficicación

En el archivo .env puedo poner cualquier contraseña o usuario? o que características tiene que tener?

Al inicializar el proyecto con "yarn dev" como se muestra en las capsulas me sale el siguiente error

catalinaortega@LAPTOP-6OJTKV30:~/grupo_ChechoTech_backend$ yarn dev
yarn run v1.22.19
warning ../package.json: No license field
$ nodemon src/index.js
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node src/index.js`
Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "catalinaortega"
    at Client._connectionCallback (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)
    at Client._handleErrorWhileConnecting (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg/lib/client.js:327:19)
    at Client._handleErrorMessage (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg/lib/client.js:347:19)
    at Connection.emit (events.js:314:20)
    at /home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9) {
  parent: error: password authentication failed for user "catalinaortega"
      at Parser.parseErrorMessage (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '335',
    routine: 'auth_failed'
  },
  original: error: password authentication failed for user "catalinaortega"
      at Parser.parseErrorMessage (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/catalinaortega/grupo_ChechoTech_backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '335',
    routine: 'auth_failed'
  }
}
[nodemon] clean exit - waiting for changes before restart

que puedo hacer para solucionarlo? estuve investigando harto rato que hacer pero no pude encontrar mucho

**Comment by catalinaortegacalderon** [comment]
lo pude arreglar cambiando la contraseña en posgres por si a alguien le sirve!

me meti a la consola de psql
psql -U tu_usuario -d tu_base_de_datos

y despues cambie la contraseña
ALTER USER catalinaortega WITH PASSWORD 'new_password';
