### ISSUE TITLE
Error acceso a base de datos con yarn start

### ISSUE THREAD

**Issue by tariztia** [IIC2513/Syllabus-S2#3]
Holaa! Tengo este problema al correr 'yarn start'. Probé haciendo lo que dijo una compañera en la issue anterior para cambiar la contraseña, pero no me solucionó el problema. Tambien probé reiniciando wsl y nada.

tariztia@LAPTOP-de-Tomas:~/web/grupo_nkaramesi_backend$ yarn start
yarn run v1.22.19
warning ../../package.json: No license field
$ node src/index.js
Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "tariztia"
    at Client._connectionCallback (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)
    at Client._handleErrorWhileConnecting (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg/lib/client.js:327:19)
    at Client._handleErrorMessage (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg/lib/client.js:347:19)
    at Connection.emit (node:events:515:28)
    at /home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:515:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3) {
  parent: error: password authentication failed for user "tariztia"
      at Parser.parseErrorMessage (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:515:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
      at Readable.push (node:internal/streams/readable:375:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '330',
    routine: 'auth_failed'
  },
  original: error: password authentication failed for user "tariztia"
      at Parser.parseErrorMessage (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/tariztia/web/grupo_nkaramesi_backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:515:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
      at Readable.push (node:internal/streams/readable:375:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '330',
    routine: 'auth_failed'
  }
}
Done in 0.59s.

Muchas graciass

**Comment by SebaValenzuela** [comment]
A mi me pasa lo mismo
![image](https://github.com/IIC2513/Syllabus-S2/assets/89088201/ed746b76-873e-41e3-bc04-1d2f71884df2)

**Comment by ElTioAndresCabezas** [comment]
Se aseguraron de colocar los datos de inicio de sesión de la base de datos dentro de su archivo .env?

Cuando no hacen eso, ocurre que sequelize trata de conectarse a la base de datos usando el usuario de Linux, y la mayoría de veces esto no funciona.

Estas son algunas cosas que pueden probar:
- Revisen que su .env tenga los datos correspondientes.
- Asegurense de instanciar correctamente estos datos en su configuración de sequelize.
- Asegurense que su `.sequelizerc` apunte a su archivo de configuración correctamente. Por ejemplo:
```
module.exports = {
  //...
  "config":path.resolve('ruta','a_tu','config.js'),
  //...
}
```
- Asegurense de que las credenciales estan bien puestas.

Intenten esto y cuentenme como les va

**Comment by SebaValenzuela** [comment]
Aun no me funciona, he hecho muchas cosas y no me resulta nada

**Comment by ElTioAndresCabezas** [comment]
> Aun no me funciona, he hecho muchas cosas y no me resulta nada

Dame el nombre de tu grupo para revisar en GitHub como tienen todo configurado.

**Comment by SebaValenzuela** [comment]
WEB-ones, eso si a mi compañero si le funciona, es problema mio

**Comment by ElTioAndresCabezas** [comment]
@SebaValenzuela Permiteme preguntarte, en donde tienes ubicado tu .env?

> [...] eso si a mi compañero si le funciona, es problema mio

Esto me indica que probablemente hay un problema con tu .env, que es el unico archivo que no comparten

**Comment by SebaValenzuela** [comment]
![image](https://github.com/IIC2513/Syllabus-S2/assets/89088201/a8aa018b-3b01-4fea-adb6-30845f6cbcd5)

**Comment by ElTioAndresCabezas** [comment]
Sé que esto es lo más típico, pero revisaste los videos acerca de la configuración de la base de datos que tenemos en el Syllabus? Estás seguro que tu y tu compañero tienen la misma configuración?

Como tienes problemas con el inicio de sesión de la base de datos, pero claramente la base de datos se está ejecutando y esta funcionando, me pregunto si tendrá que ver con algo que no está configurado correctamente.
